---
apiVersion: v2
name: external-dns
description: Umbrella chart for external-dns (kubernetes-sigs)
type: application
version: 1.0.0
appVersion: "v0.19.0"
dependencies:
  - name: external-dns
    version: 1.19.0
    repository: https://kubernetes-sigs.github.io/external-dns/
