---
apiVersion: v2
name: external-secrets
description: Umbrella chart for external-secrets (external-secrets)
type: application
version: 1.0.0
appVersion: "v1.1.0"
dependencies:
  - name: external-secrets
    version: 1.1.0
    repository: https://charts.external-secrets.io
