---
apiVersion: v2
name: traefik
description: Umbrella chart for traefik (traefik)
type: application
version: 1.0.0
appVersion: "v3.6.2"
dependencies:
  - name: traefik
    version: 37.0.0
    repository: https://traefik.github.io/charts
